'use strict';

const StellarSdk = require('@stellar/stellar-sdk');

// Generate a deterministic secret for testing
const TEST_SECRET = StellarSdk.Keypair.random().secret();
const TEST_PUBLIC = StellarSdk.Keypair.fromSecret(TEST_SECRET).publicKey();

function freshSep10Module(secret, nodeEnv) {
  jest.resetModules();
  process.env.SEP10_SIGNING_SECRET = secret;
  process.env.NODE_ENV = nodeEnv;
  const mod = require('../services/sep10');
  return mod;
}

describe('SERVER_KEYPAIR determinism', () => {
  afterEach(() => {
    delete process.env.SEP10_SIGNING_SECRET;
    delete process.env.NODE_ENV;
    jest.resetModules();
  });

  test('SERVER_KEYPAIR.publicKey() is stable across two separate loads with the same secret', () => {
    const mod1 = freshSep10Module(TEST_SECRET, 'test');
    const mod2 = freshSep10Module(TEST_SECRET, 'test');

    expect(mod1.SERVER_KEYPAIR.publicKey()).toBe(TEST_PUBLIC);
    expect(mod2.SERVER_KEYPAIR.publicKey()).toBe(TEST_PUBLIC);
    expect(mod1.SERVER_KEYPAIR.publicKey()).toBe(mod2.SERVER_KEYPAIR.publicKey());
  });

  test('SERVER_KEYPAIR public key matches the derived key from the secret', () => {
    const mod = freshSep10Module(TEST_SECRET, 'test');
    expect(mod.SERVER_KEYPAIR.publicKey()).toBe(TEST_PUBLIC);
    expect(mod.SERVER_KEYPAIR.secret()).toBe(TEST_SECRET);
  });

  test('challenge generated by one instance verifies on another', () => {
    const clientKeypair = StellarSdk.Keypair.random();
    const clientPub = clientKeypair.publicKey();

    const modA = freshSep10Module(TEST_SECRET, 'test');
    const challengeXdr = modA.generateChallenge(clientPub);

    const modB = freshSep10Module(TEST_SECRET, 'test');

    // Client signs the challenge
    const parsed = StellarSdk.TransactionBuilder.fromXDR(challengeXdr, StellarSdk.Networks.TESTNET);
    parsed.sign(clientKeypair);
    const signedXdr = parsed.toEnvelope().toXDR('base64');

    const verified = modB.verifyChallenge(clientPub, signedXdr);
    expect(verified).toBe(true);
  });

  test('challenge survives process restart simulation (same secret, new module load)', () => {
    const clientKeypair = StellarSdk.Keypair.random();
    const clientPub = clientKeypair.publicKey();

    const modBefore = freshSep10Module(TEST_SECRET, 'test');
    const challengeXdr = modBefore.generateChallenge(clientPub);

    // Client signs the challenge
    const parsed = StellarSdk.TransactionBuilder.fromXDR(challengeXdr, StellarSdk.Networks.TESTNET);
    parsed.sign(clientKeypair);
    const signedXdr = parsed.toEnvelope().toXDR('base64');

    const modAfter = freshSep10Module(TEST_SECRET, 'test');
    const verified = modAfter.verifyChallenge(clientPub, signedXdr);

    expect(verified).toBe(true);
  });

  test('verifyChallenge returns false when secrets differ', () => {
    const clientKeypair = StellarSdk.Keypair.random();
    const clientPub = clientKeypair.publicKey();

    const secret1 = StellarSdk.Keypair.random().secret();
    const secret2 = StellarSdk.Keypair.random().secret();

    const modA = freshSep10Module(secret1, 'test');
    const challengeXdr = modA.generateChallenge(clientPub);

    // Client signs
    const parsed = StellarSdk.TransactionBuilder.fromXDR(challengeXdr, StellarSdk.Networks.TESTNET);
    parsed.sign(clientKeypair);
    const signedXdr = parsed.toEnvelope().toXDR('base64');

    const modB = freshSep10Module(secret2, 'test');
    const verified = modB.verifyChallenge(clientPub, signedXdr);

    expect(verified).toBe(false);
  });
});

describe('SERVER_KEYPAIR — production without secret', () => {
  beforeEach(() => {
    delete process.env.SEP10_SIGNING_SECRET;
    process.env.NODE_ENV = 'production';
    jest.resetModules();
  });

  afterEach(() => {
    delete process.env.SEP10_SIGNING_SECRET;
    delete process.env.NODE_ENV;
    jest.resetModules();
  });

  test('fails fast with a clear error when SECRET is missing in production', () => {
    expect(() => require('../services/sep10')).toThrow(
      /SEP10_SIGNING_SECRET must be set in production/
    );
  });
});

describe('SERVER_KEYPAIR — no secret in development', () => {
  beforeEach(() => {
    delete process.env.SEP10_SIGNING_SECRET;
    process.env.NODE_ENV = 'development';
    jest.resetModules();
  });

  afterEach(() => {
    delete process.env.SEP10_SIGNING_SECRET;
    delete process.env.NODE_ENV;
    jest.resetModules();
  });

  test('falls back to random keypair in development when no secret is set', () => {
    const mod = require('../services/sep10');
    expect(mod.SERVER_KEYPAIR).toBeDefined();
    expect(mod.SERVER_KEYPAIR.publicKey()).toBeTruthy();
    expect(mod.SERVER_KEYPAIR.secret()).toBeTruthy();
  });
});
